# Generated by Django 6.0 on 2025-12-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_chatmessage_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
