# Generated by Django 6.0 on 2025-12-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
