# Generated by Django 6.0 on 2026-02-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock_quantity_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
