# Generated by Django 6.0 on 2025-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Merchandise', 'Merchandise')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
