# Generated by Django 6.0 on 2026-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_stock_adjusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
