# Generated by Django 4.2.11 on 2025-12-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_stripe_payment_intent_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='paypal_order_id',
        ),
    ]
