# Generated by Django 6.0 on 2025-12-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
