# Generated by Django 6.0 on 2025-12-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
    ]
