# Generated by Django 6.0 on 2025-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_price_id',
            new_name='stripe_one_time_price_id',
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_subscription_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
