# Generated by Django 6.0 on 2025-12-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='free_item_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_free_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
