# Generated by Django 6.0 on 2025-12-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderitem_free_item_size_orderitem_is_free_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
