# Generated by Django 6.0 on 2025-12-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_name_snapshot',
            field=models.CharField(blank=True, help_text='Color name at time of order', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_snapshot',
            field=models.CharField(blank=True, help_text='Hex color at time of order', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_snapshot',
            field=models.CharField(blank=True, help_text='Size at time of order', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('', ''), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=3)),
                ('color_hex', models.CharField(help_text='Hex color code, e.g., #FF0000', max_length=7)),
                ('color_name', models.CharField(help_text='Human-readable color name, e.g., Red', max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text="Optional price override. If not set, uses product's discounted_price", max_digits=10, null=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit, e.g., PROD-001-S-RED', max_length=100, unique=True)),
                ('stripe_one_time_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'ordering': ['size', 'color_name'],
                'unique_together': {('product', 'size', 'color_hex')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Specific size/color variant selected', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Reference to the variant that was ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
    ]
