# Generated by Django 6.0 on 2025-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_orderitem_color_name_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stripe_one_time_price_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stripe_subscription_price_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('', ''), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
    ]
