# Generated by Django 6.0 on 2025-12-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_productvariant_stripe_one_time_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_snapshot',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
