# Generated by Django 6.0 on 2025-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_cartitem_variant_remove_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.JSONField(blank=True, default=list, help_text="Array of color objects, e.g. [{'hex': '#FF0000', 'name': 'Red'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text="Array of available sizes, e.g. ['S', 'M', 'L']"),
        ),
    ]
