# Generated by Django 6.0 on 2025-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_available_colors_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
