# Generated by Django 6.0 on 2025-12-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_order_user'),
    ]

    operations = [
    ]
