# Generated by Django 6.0 on 2025-12-31 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_alter_order_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, help_text="Optional customer email for guest orders", max_length=254, null=True),
        ),
    ]
