# Generated by Django 6.0 on 2026-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_merge_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
