# Generated by Django 6.0 on 2026-01-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_contactmessage_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_checkout_session_id',
            new_name='nowpayments_payment_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stripe_one_time_price_id',
            new_name='nowpayments_product_id',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='stripe_subscription_item_id',
            new_name='nowpayments_subscription_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_subscription_price_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
    ]
