# Generated by Django 6.0 on 2026-02-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_usersubscription_email_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
